INPUT_FOLDER_PATH = "./input/"
OUTPUT_FOLDER_PATH = "./output/"
RESUME_TEMPLATE_FILE = "resume_template.html"
RESUME_DATA_FILE = "resume_data.json"
RESUME_HTML_FILE = "resume.html"
RESUME_PDF_FILE = "resume.pdf"